export const theme = {
    colors: {
      primary: '#AA2E2E',
      secondary: '#FF5959',
      gray: '#5A6474',
      textHeader: '#AA2E2E',
      borderColor: '#E1E3E6',
      labelColor: '#757D8A',
      dividerColor: '#C3C7CE',
      txtcolor: 'black',
      gren: '#07A287',
      btntxtcolor: 'white',
      btncolor: '#AA2E2E',
      placeholdertxt: 'lightgrey',
      loaderColor: 'white',
      background: 'white',
      bg_color: '#f4f4f4',
      headerTintColor: 'white',
      shadow: 'lightgrey',
      white: 'white',
      green: '#0c8d01',
      headingColor: 'lightgrey',
      lightgrey: '#BAB9B9',
      lightBlue: '#08adff',
      darkBlue: '#7b68ee',
      lightgreen: '#6bc950',
      lightPrimary: '#b22334',
      lightBlack: '#3d3e3d',
      black: '#000000',
      badgeColor: '#FBCECE',
    },
  };